// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the module genesis state
type GenesisState struct {
	// Params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// List of prices to initialize the store with
	Prices []Price `protobuf:"bytes,2,rep,name=prices,proto3" json:"prices"`
	// List of registered providers
	Providers []ProviderInfo `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers"`
	// List of validator price submissions
	ValidatorPrices []ValidatorPrice `protobuf:"bytes,4,rep,name=validator_prices,json=validatorPrices,proto3" json:"validator_prices"`
	// List of oracle metadata
	OracleInfos []OracleInfo `protobuf:"bytes,5,rep,name=oracle_infos,json=oracleInfos,proto3" json:"oracle_infos"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b982a0a6345d1d, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPrices() []Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

func (m *GenesisState) GetProviders() []ProviderInfo {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *GenesisState) GetValidatorPrices() []ValidatorPrice {
	if m != nil {
		return m.ValidatorPrices
	}
	return nil
}

func (m *GenesisState) GetOracleInfos() []OracleInfo {
	if m != nil {
		return m.OracleInfos
	}
	return nil
}

// Params defines the set of module parameters.
type Params struct {
	// Minimum number of validators required for median calculation
	MinValidatorsForMedian uint32 `protobuf:"varint,1,opt,name=min_validators_for_median,json=minValidatorsForMedian,proto3" json:"min_validators_for_median,omitempty"`
	// Maximum age of price before considered stale (in seconds)
	MaxPriceAge int64 `protobuf:"varint,2,opt,name=max_price_age,json=maxPriceAge,proto3" json:"max_price_age,omitempty"`
	// Whether to allow negative one (-1) settlement prices
	AllowNegativeSettlement bool `protobuf:"varint,3,opt,name=allow_negative_settlement,json=allowNegativeSettlement,proto3" json:"allow_negative_settlement,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b982a0a6345d1d, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinValidatorsForMedian() uint32 {
	if m != nil {
		return m.MinValidatorsForMedian
	}
	return 0
}

func (m *Params) GetMaxPriceAge() int64 {
	if m != nil {
		return m.MaxPriceAge
	}
	return 0
}

func (m *Params) GetAllowNegativeSettlement() bool {
	if m != nil {
		return m.AllowNegativeSettlement
	}
	return false
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "oracle.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "oracle.v1.Params")
}

func init() { proto.RegisterFile("oracle/v1/genesis.proto", fileDescriptor_14b982a0a6345d1d) }

var fileDescriptor_14b982a0a6345d1d = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x3d, 0x6f, 0x13, 0x31,
	0x18, 0x3e, 0x27, 0x25, 0xa2, 0x4e, 0x23, 0x5a, 0x8b, 0x92, 0x4b, 0x86, 0x4b, 0x94, 0x29, 0x62,
	0xb8, 0x53, 0xcb, 0x44, 0x91, 0x90, 0xe8, 0xc0, 0x97, 0xc4, 0x87, 0x52, 0x89, 0x81, 0xc5, 0x72,
	0x2f, 0xce, 0xd5, 0xd2, 0xd9, 0xef, 0xc9, 0x36, 0x47, 0xf8, 0x0b, 0x4c, 0x8c, 0x8c, 0xfd, 0x09,
	0x8c, 0x6c, 0xac, 0x1d, 0x3b, 0x32, 0x21, 0x94, 0x0c, 0xf0, 0x33, 0x50, 0xec, 0xe3, 0x72, 0x5d,
	0x4e, 0xaf, 0x9e, 0xcf, 0xf7, 0x6c, 0xe3, 0x3e, 0x68, 0x96, 0xe6, 0x3c, 0x29, 0x8f, 0x92, 0x8c,
	0x2b, 0x6e, 0x84, 0x89, 0x0b, 0x0d, 0x16, 0xc8, 0xae, 0x27, 0xe2, 0xf2, 0x68, 0x78, 0x37, 0x83,
	0x0c, 0x1c, 0x9a, 0x6c, 0x26, 0x2f, 0x18, 0x1e, 0x30, 0x29, 0x14, 0x24, 0xee, 0x5b, 0x41, 0x87,
	0xdb, 0x30, 0x63, 0x99, 0xe5, 0x1e, 0x9e, 0x7c, 0x6f, 0xe1, 0xbd, 0x67, 0x3e, 0xfc, 0x6c, 0x03,
	0x93, 0x04, 0x77, 0x0a, 0xa6, 0x99, 0x34, 0x21, 0x1a, 0xa3, 0x69, 0xf7, 0xf8, 0x20, 0xae, 0xcb,
	0xe2, 0xb7, 0x8e, 0x38, 0xdd, 0xb9, 0xfa, 0x35, 0x0a, 0x66, 0x95, 0x8c, 0xc4, 0xb8, 0x53, 0x68,
	0x91, 0x72, 0x13, 0xb6, 0xc6, 0xed, 0x69, 0xf7, 0x78, 0xbf, 0x69, 0xd8, 0x10, 0xb5, 0xde, 0xa9,
	0xc8, 0x23, 0xbc, 0x5b, 0x68, 0x28, 0xc5, 0x9c, 0x6b, 0x13, 0xb6, 0x9d, 0xa5, 0x7f, 0xc3, 0xe2,
	0xb9, 0x17, 0x6a, 0x01, 0x95, 0x73, 0xab, 0x27, 0x2f, 0xf1, 0x7e, 0xc9, 0x72, 0x31, 0x67, 0x16,
	0x34, 0xad, 0x6a, 0x77, 0x5c, 0xc6, 0xa0, 0x91, 0xf1, 0xee, 0xbf, 0xa4, 0xd9, 0x7f, 0xa7, 0xbc,
	0x81, 0x1a, 0xf2, 0x18, 0xef, 0x79, 0x0b, 0x15, 0x6a, 0x01, 0x26, 0xbc, 0xe5, 0x72, 0x0e, 0x1b,
	0x39, 0x6f, 0xdc, 0xd4, 0xd8, 0xa4, 0x0b, 0x35, 0x62, 0x26, 0x3f, 0x10, 0xee, 0xf8, 0x13, 0x21,
	0x0f, 0xf1, 0x40, 0x0a, 0x45, 0xeb, 0x06, 0x43, 0x17, 0xa0, 0xa9, 0xe4, 0x73, 0xc1, 0x94, 0x3b,
	0xc7, 0xde, 0xec, 0x9e, 0x14, 0xaa, 0xde, 0xcb, 0x3c, 0x05, 0xfd, 0xca, 0xb1, 0x64, 0x82, 0x7b,
	0x92, 0x2d, 0xfd, 0xbf, 0x50, 0x96, 0xf1, 0xb0, 0x35, 0x46, 0xd3, 0xf6, 0xac, 0x2b, 0xd9, 0xd2,
	0xed, 0xf9, 0x24, 0xe3, 0xe4, 0x04, 0x0f, 0x58, 0x9e, 0xc3, 0x47, 0xaa, 0x78, 0xc6, 0xac, 0x28,
	0x39, 0x35, 0xdc, 0xda, 0x9c, 0x4b, 0xae, 0x6c, 0xd8, 0x1e, 0xa3, 0xe9, 0xed, 0x59, 0xdf, 0x09,
	0x5e, 0x57, 0xfc, 0x59, 0x4d, 0x9f, 0x0c, 0xbf, 0x5e, 0x8e, 0x82, 0xbf, 0x97, 0x23, 0xf4, 0xf9,
	0xcf, 0xb7, 0xfb, 0xbd, 0xea, 0x11, 0xf8, 0xab, 0x3b, 0x7d, 0x7e, 0xb5, 0x8a, 0xd0, 0xf5, 0x2a,
	0x42, 0xbf, 0x57, 0x11, 0xfa, 0xb2, 0x8e, 0x82, 0xeb, 0x75, 0x14, 0xfc, 0x5c, 0x47, 0xc1, 0xfb,
	0x38, 0x13, 0xf6, 0xe2, 0xc3, 0x79, 0x9c, 0x82, 0x4c, 0x34, 0xe4, 0x79, 0x7a, 0xc1, 0x84, 0x32,
	0xdb, 0x31, 0x59, 0x26, 0x55, 0x94, 0xfd, 0x54, 0x70, 0x73, 0xde, 0x71, 0xaf, 0xe9, 0xc1, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xb1, 0x92, 0xec, 0xb3, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinValidatorsForMedian != that1.MinValidatorsForMedian {
		return false
	}
	if this.MaxPriceAge != that1.MaxPriceAge {
		return false
	}
	if this.AllowNegativeSettlement != that1.AllowNegativeSettlement {
		return false
	}
	return true
}
func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OracleInfos) > 0 {
		for iNdEx := len(m.OracleInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ValidatorPrices) > 0 {
		for iNdEx := len(m.ValidatorPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Providers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Prices) > 0 {
		for iNdEx := len(m.Prices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowNegativeSettlement {
		i--
		if m.AllowNegativeSettlement {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MaxPriceAge != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxPriceAge))
		i--
		dAtA[i] = 0x10
	}
	if m.MinValidatorsForMedian != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinValidatorsForMedian))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Prices) > 0 {
		for _, e := range m.Prices {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Providers) > 0 {
		for _, e := range m.Providers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorPrices) > 0 {
		for _, e := range m.ValidatorPrices {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleInfos) > 0 {
		for _, e := range m.OracleInfos {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinValidatorsForMedian != 0 {
		n += 1 + sovGenesis(uint64(m.MinValidatorsForMedian))
	}
	if m.MaxPriceAge != 0 {
		n += 1 + sovGenesis(uint64(m.MaxPriceAge))
	}
	if m.AllowNegativeSettlement {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prices = append(m.Prices, Price{})
			if err := m.Prices[len(m.Prices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, ProviderInfo{})
			if err := m.Providers[len(m.Providers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorPrices = append(m.ValidatorPrices, ValidatorPrice{})
			if err := m.ValidatorPrices[len(m.ValidatorPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleInfos = append(m.OracleInfos, OracleInfo{})
			if err := m.OracleInfos[len(m.OracleInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValidatorsForMedian", wireType)
			}
			m.MinValidatorsForMedian = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinValidatorsForMedian |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPriceAge", wireType)
			}
			m.MaxPriceAge = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPriceAge |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowNegativeSettlement", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowNegativeSettlement = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
