// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: oracle/v1/query.proto

package oraclev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName               = "/oracle.v1.Query/Params"
	Query_GetPrice_FullMethodName             = "/oracle.v1.Query/GetPrice"
	Query_GetProviderPrice_FullMethodName     = "/oracle.v1.Query/GetProviderPrice"
	Query_GetAllProviderPrices_FullMethodName = "/oracle.v1.Query/GetAllProviderPrices"
	Query_GetProvider_FullMethodName          = "/oracle.v1.Query/GetProvider"
	Query_GetAllProviders_FullMethodName      = "/oracle.v1.Query/GetAllProviders"
	Query_GetOracleInfo_FullMethodName        = "/oracle.v1.Query/GetOracleInfo"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries all parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetPrice returns the price of a specific asset
	GetPrice(ctx context.Context, in *QueryGetPriceRequest, opts ...grpc.CallOption) (*QueryGetPriceResponse, error)
	// GetProviderPrice returns price from a specific provider
	GetProviderPrice(ctx context.Context, in *QueryGetProviderPriceRequest, opts ...grpc.CallOption) (*QueryGetProviderPriceResponse, error)
	// GetAllProviderPrices returns all prices from a specific provider
	GetAllProviderPrices(ctx context.Context, in *QueryGetAllProviderPricesRequest, opts ...grpc.CallOption) (*QueryGetAllProviderPricesResponse, error)
	// GetProvider returns information about a registered provider
	GetProvider(ctx context.Context, in *QueryGetProviderRequest, opts ...grpc.CallOption) (*QueryGetProviderResponse, error)
	// GetAllProviders returns all registered providers
	GetAllProviders(ctx context.Context, in *QueryGetAllProvidersRequest, opts ...grpc.CallOption) (*QueryGetAllProvidersResponse, error)
	// GetOracleInfo returns oracle metadata for a symbol
	GetOracleInfo(ctx context.Context, in *QueryGetOracleInfoRequest, opts ...grpc.CallOption) (*QueryGetOracleInfoResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPrice(ctx context.Context, in *QueryGetPriceRequest, opts ...grpc.CallOption) (*QueryGetPriceResponse, error) {
	out := new(QueryGetPriceResponse)
	err := c.cc.Invoke(ctx, Query_GetPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProviderPrice(ctx context.Context, in *QueryGetProviderPriceRequest, opts ...grpc.CallOption) (*QueryGetProviderPriceResponse, error) {
	out := new(QueryGetProviderPriceResponse)
	err := c.cc.Invoke(ctx, Query_GetProviderPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllProviderPrices(ctx context.Context, in *QueryGetAllProviderPricesRequest, opts ...grpc.CallOption) (*QueryGetAllProviderPricesResponse, error) {
	out := new(QueryGetAllProviderPricesResponse)
	err := c.cc.Invoke(ctx, Query_GetAllProviderPrices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProvider(ctx context.Context, in *QueryGetProviderRequest, opts ...grpc.CallOption) (*QueryGetProviderResponse, error) {
	out := new(QueryGetProviderResponse)
	err := c.cc.Invoke(ctx, Query_GetProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllProviders(ctx context.Context, in *QueryGetAllProvidersRequest, opts ...grpc.CallOption) (*QueryGetAllProvidersResponse, error) {
	out := new(QueryGetAllProvidersResponse)
	err := c.cc.Invoke(ctx, Query_GetAllProviders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetOracleInfo(ctx context.Context, in *QueryGetOracleInfoRequest, opts ...grpc.CallOption) (*QueryGetOracleInfoResponse, error) {
	out := new(QueryGetOracleInfoResponse)
	err := c.cc.Invoke(ctx, Query_GetOracleInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params queries all parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetPrice returns the price of a specific asset
	GetPrice(context.Context, *QueryGetPriceRequest) (*QueryGetPriceResponse, error)
	// GetProviderPrice returns price from a specific provider
	GetProviderPrice(context.Context, *QueryGetProviderPriceRequest) (*QueryGetProviderPriceResponse, error)
	// GetAllProviderPrices returns all prices from a specific provider
	GetAllProviderPrices(context.Context, *QueryGetAllProviderPricesRequest) (*QueryGetAllProviderPricesResponse, error)
	// GetProvider returns information about a registered provider
	GetProvider(context.Context, *QueryGetProviderRequest) (*QueryGetProviderResponse, error)
	// GetAllProviders returns all registered providers
	GetAllProviders(context.Context, *QueryGetAllProvidersRequest) (*QueryGetAllProvidersResponse, error)
	// GetOracleInfo returns oracle metadata for a symbol
	GetOracleInfo(context.Context, *QueryGetOracleInfoRequest) (*QueryGetOracleInfoResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetPrice(context.Context, *QueryGetPriceRequest) (*QueryGetPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedQueryServer) GetProviderPrice(context.Context, *QueryGetProviderPriceRequest) (*QueryGetProviderPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderPrice not implemented")
}
func (UnimplementedQueryServer) GetAllProviderPrices(context.Context, *QueryGetAllProviderPricesRequest) (*QueryGetAllProviderPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProviderPrices not implemented")
}
func (UnimplementedQueryServer) GetProvider(context.Context, *QueryGetProviderRequest) (*QueryGetProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedQueryServer) GetAllProviders(context.Context, *QueryGetAllProvidersRequest) (*QueryGetAllProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProviders not implemented")
}
func (UnimplementedQueryServer) GetOracleInfo(context.Context, *QueryGetOracleInfoRequest) (*QueryGetOracleInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOracleInfo not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPrice(ctx, req.(*QueryGetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProviderPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProviderPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProviderPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetProviderPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProviderPrice(ctx, req.(*QueryGetProviderPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllProviderPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllProviderPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllProviderPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetAllProviderPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllProviderPrices(ctx, req.(*QueryGetAllProviderPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProvider(ctx, req.(*QueryGetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetAllProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllProviders(ctx, req.(*QueryGetAllProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetOracleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetOracleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetOracleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetOracleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetOracleInfo(ctx, req.(*QueryGetOracleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oracle.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetPrice",
			Handler:    _Query_GetPrice_Handler,
		},
		{
			MethodName: "GetProviderPrice",
			Handler:    _Query_GetProviderPrice_Handler,
		},
		{
			MethodName: "GetAllProviderPrices",
			Handler:    _Query_GetAllProviderPrices_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _Query_GetProvider_Handler,
		},
		{
			MethodName: "GetAllProviders",
			Handler:    _Query_GetAllProviders_Handler,
		},
		{
			MethodName: "GetOracleInfo",
			Handler:    _Query_GetOracleInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/v1/query.proto",
}
